apiVersion: v1
kind: Service
metadata:
  labels:
    app: mywebsvc
  name: {{ .Values.service.name }}
spec:
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: 80
  selector:
  run: nginx
  type: {{ .Values.service.type }}

